######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 27 23:43:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += TripPlanner.h ../Shared.h
SOURCES += main.cpp TripPlanner.cpp ../Shared.cpp
